version: '3'


services:
  redis:
    restart: unless-stopped
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis_data:/data
    # env_file: # FIXME
    #   - ./env/redis.env
  dramatiq_worker:
    restart: unless-stopped
    container_name: dramatiq_worker
    build:
      context: .
      dockerfile: ./dockerfiles/Worker.Dockerfile
    # env_file:  # FIXME!
    #   - ./env/imdb.env
    depends_on:
      - redis
    expose:
      - "9191"
    volumes:
      - dbdata:/home/app/database:rw
    command: tail -f /dev/null #python -m dramatiq tasks
    # command: python -m dramatiq tasks:redis
    # entrypoint: ./start-workers.sh
  server:
    restart: unless-stopped
    container_name: flask_server
    build:
      context: .
      dockerfile: ./dockerfiles/Server.Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - dbdata:/home/app/database:rw
      - static_volume:/home/app/static:rw
    command: python -m gunicorn wsgi:app --preload --bind 0.0.0.0:8000
    # env_file:  FIXME
    #   - ./env/vm.env
    depends_on:
      - redis
      - dramatiq_worker

volumes:
  redis_data:
  dbdata:
  static_volume:
