version: 1
disable_existing_loggers: true

# Ascii colors
# https://gist.github.com/Prakasaka/219fe5695beeb4d6311583e79933a009#file-bash-colors-md

formatters:
  standard:
      format: "\e[0;32m%(asctime)s\e[0m | \e[1;37m<%(levelname)s>\e[0m | \e[0;34m%(name)s\e[0m | \e[1;33m%(message)s\e[0m"
  verbose:
      format: "\e[0;32m%(asctime)s\e[0m | \e[0;34m%(name)s\e[0m.\e[0;35m%(funcName)s\e[0m:\e[0;36m%(lineno)d\e[0m \e[1;37m<%(levelname)s>\e[0m | \e[0;31m%(message)s\e[0m"
  multi_process:
    format: "%(asctime)s; %(levelname)-8s; [%(thread;)s]; %(name)-35s; %(funcName)-20s;%(lineno)-4d: %(message)s"
  multi_thread:
    format: "%(asctime)s; %(levelname)-8s; [%(process)d]; %(name)-35s; %(funcName)-20s;%(lineno)-4d: %(message)s"
  multi_line:
    format: "Level:\e[1;37m<%(levelname)s>\e[0m\nTime: \e[0;32m%(asctime)s\e[0m\nProcess: \e[4;34m%(process)d\e[0m\nThread: \e[4;34m%(thread)s\e[0m\nLogger: \e[0;92m%(name)s\e[0m\nPath: \e[0;93m%(module)s\e[0m:\e[4;33m%(lineno)d\e[0m\nFunction: \e[0;35m%(funcName)s\e[0m\n\e[4;31mMessage:\e[0m \e[4;37m%(message)s\e[0m\n"

handlers:
  console_dev:
    level: DEBUG
    class: logging.StreamHandler
    formatter: multi_line
    stream : ext://sys.stdout
  console_error:
    level: ERROR
    class: logging.StreamHandler
    formatter: verbose
    stream : ext://sys.stdout
  console_prod:
    level: INFO
    class: logging.StreamHandler
    formatter: standard
    stream : ext://sys.stdout

root:
    level: DEBUG
    handlers: [console_dev]
    propogate: yes


loggers:
    logging_setup:
        level: INFO
        handlers: [console_prod]
        propogate: yes

